# Generated by Django 5.0.4 on 2024-05-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_student_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmanagement',
            name='uid',
        ),
    ]
