# Generated by Django 5.0.4 on 2024-05-03 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_bookmanagement_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributedbooks',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
