# Generated by Django 5.0.4 on 2024-05-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_distributedbooks_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='uid',
        ),
    ]
