# Generated by Django 5.0.4 on 2024-05-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_bookmanagement_uid_distributedbooks_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='due',
            field=models.DateField(null=True),
        ),
    ]
