# Generated by Django 5.0.4 on 2024-05-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_student_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
