# Generated by Django 5.0.4 on 2024-05-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='name',
        ),
    ]
