# Generated by Django 5.0.4 on 2024-05-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
