# Generated by Django 5.0.4 on 2024-05-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_student_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmanagement',
            name='stock',
            field=models.IntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='DistributedBooks',
        ),
    ]
